under_picture_pictures("sample_high_tone.wav")       %自分の声(高音のつもり)
under_picture_pictures("sample_low_tone.wav")        %自分の声(低音)
under_picture_pictures("sample_high_low_tone.wav")   %自分の声(高低差あり)
under_picture_pictures("sample_doremi.mp3")
under_picture_pictures("sample_drum1.wav")
under_picture_pictures("sample_fue1.wav")
under_picture_pictures("sample_sample_gone.wav")
under_picture_pictures("sample_suzu1.wav")
under_picture_pictures("sample_triangle.wav")